databases:
  - name: newdb
    plan: free
    databaseName: garagerental
    user: rk

services:
  - type: web
    plan: free
    name: garagerental
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn garagerental.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: newdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4